betagouv/signalconso-dashboard-react

src/core/i18n/localization/fr.ts
src/feature/Stats/StatsProUserPanel.tsx

Adding new pro account creation curve

Adding new pro stat

---

src/core/client/company/Company.ts
src/core/client/website/Website.ts
src/feature/Companies/CompaniesRegistered.tsx
src/feature/ReportedWebsites/SelectWebsiteIdentification/SelectWebsiteAssociation.tsx

* TRELLO-1169: adding headoffice & isOpen to company

TRELLO-1169: adding headoffice & isOpen to company (#227)

---

src/core/client/report/Report.ts
src/core/client/report/ReportsClient.ts
src/core/i18n/localization/fr.ts
src/feature/Report/Report.tsx
src/feature/Report/ReportAdminResolution.tsx

* TRELLO-2045: report completion admin action

Trello 2045 (#438)

---

src/core/i18n/localization/fr.ts
src/feature/AdminTools/Tools.tsx
src/feature/Companies/Companies.tsx
src/feature/Companies/CompaniesToActivate.tsx
src/feature/Companies/CompaniesToFollowUp.tsx
src/feature/ReportsPro/ReportsPro.tsx
src/feature/Stats/Stats.tsx
src/feature/Users/ConsumerListPending.tsx
src/feature/Users/UserAuthAttempts.tsx
src/feature/Users/UsersList.tsx
src/shared/Datatable/Datatable.tsx
src/shared/Label.tsx
src/shared/Page/PageTitle.tsx
src/shared/Panel/Panel.tsx

Renommage de certains titres
Titres plus gros
Ajout d'une phrase sur la page de statistiques
Réorganisation de l'ordre des colonnes de la vue pro des signalements

small ux improvements

---

src/App.tsx
src/core/Layout/LayoutContext.tsx
src/core/Layout/Sidebar/Sidebar.tsx
src/core/ScSidebar/ScSidebar.tsx
src/core/plugins/Matomo.ts

Utilisé sur uniquement 2% des pages vues
à valider avec GR quand même

UX: retrait de la feature de pin/unpin la sidebar

---

src/feature/Report/File/ReportFile.tsx

Ajustement de la taille de la modal des pièces jointes en fonction de la taille de l'écran

Adjust Attachment Modal Size

---

src/feature/Reports/CompanyNameDetails.tsx
src/feature/ReportsPro/buildReportColumns.tsx

* Highlight unread reports in bold on pro view
* Highlight unread reports in bold on pro view
---------

MEP Highlight unread reports in bold on pro view (#534)

---

src/core/ScSidebar/ScSidebar.tsx
src/core/client/event/Event.ts
src/core/client/report/Report.ts
src/core/client/report/ReportSearch.ts
src/core/client/report/ReportsClient.ts
src/feature/CompanyAccesses/CompanyAccesses.tsx
src/feature/Report/Event/ReportEvents.tsx
src/feature/Report/ReportConsumer/ReportConsumer.tsx
src/feature/Reports/Reports.tsx
src/feature/ReportsPro/buildReportColumns.tsx
src/feature/Settings/Settings.tsx
src/shared/UserNameLabel.tsx

* TRELLO-2236 : add user answerer to pro closed reports

Trello 2236 (#554)

---

src/core/client/barcode/BarcodeProduct.ts
src/feature/Report/ReportBarcodeProduct.tsx

* [TRELLO-2477] Display info when product is not found on GS1
* [TRELLO-2477] Format

MEP [TRELLO-2477] Display info when product is not found on GS1 (#650)

---

src/alexlibs/ts-utils/common/fnSwitch/FnSwitch.ts
src/core/client/async-file/AsyncFileClient.ts
src/core/client/file/FileClient.ts
src/core/client/website/WebsiteClient.ts
src/core/helper/utils.ts
src/core/i18n/localization/fr.ts
src/feature/AdminTools/DeleteSpamReportsAdminTool.tsx
src/feature/Company/CompanyChartPanel.tsx
src/feature/Company/companyStatsNumberWidgets.tsx
src/feature/CompanyAccesses/CompanyAccesses.tsx
src/feature/Login/WelcomePage.tsx
src/feature/Reports/AdvancedReportsFilter.tsx
src/shared/Datatable/Datatable.tsx
src/shared/Datepicker.tsx
src/shared/ExportPopperBtn.tsx
src/shared/Panel/simplePanels.tsx

* TRELLO-2517 : improve export ux

TRELLO-2517 : improve export ux (#666)

---

src/core/ScSidebar/ScSidebar.tsx
src/core/client/authenticate/Authenticate.ts
src/core/client/user/User.ts
src/core/client/user/UserClient.ts
src/core/context/ConnectedContext.tsx
src/core/queryhooks/userQueryHooks.ts
src/feature/Users/UserAdminInvitationDialog.tsx
src/feature/Users/UserAgentInvitationDialog.tsx
src/feature/Users/Users.tsx
src/feature/Users/UsersList.tsx

* [TRELLO-2448] Rework roles to include SuperAdmin/ReadOnlyAdmin
* [TRELLO-2448] Format
* [TRELLO-2448] Popup to invite different types of admins

MEP [TRELLO-2448] Rework roles to include SuperAdmin/ReadOnlyAdmin (#668)

---

src/alexlibs/mui-extension/Modal.tsx
src/core/i18n/localization/fr.ts
src/feature/Report/ReportPro.tsx
src/feature/Reports/DatatableToolbarComponent.tsx
src/feature/Reports/reportsColumns.tsx
src/feature/ReportsPro/ReportsPro.tsx
src/feature/ReportsPro/buildReportColumns.tsx

* TRELLO-2531 : Adding download capabilities to pro interface

Trello 2531 (#672)

---

src/core/client/event/Event.ts
src/feature/Report/Event/ReportEvents.tsx

* [TRELLO-2591] Add events when user access is created / removed
* [TRELLO-2591] Clean code

MEP [TRELLO-2591] Add events when user access is created / removed (#686)

---

src/core/client/auth-attempts/AuthAttemptClient.ts
src/core/client/reported-phone/ReportedPhoneClient.ts
src/core/client/website/WebsiteClient.ts
src/core/helper/Paginate.ts
src/core/queryhooks/phoneQueryHooks.ts
src/feature/ReportedPhones/ReportedPhones.tsx

* [TRELLO-2608] Rework some request scanning the whole report table
* [TRELLO-2608] Rework some request scanning the whole report table
* [TRELLO-2608] Fix

MEP [TRELLO-2608] Rework some request scanning the whole report table (#706)

---

src/core/client/website/Website.ts
src/core/client/website/WebsiteClient.ts
src/core/queryhooks/websiteQueryHooks.ts
src/feature/ReportedWebsites/WebsitesFilters.tsx
src/feature/ReportedWebsites/WebsitesInvestigation.tsx

* [TRELLO-2711] Websites page refactoring & marketplaces handling
* [TRELLO-2711] Format

MEP [TRELLO-2711] Websites page refactoring & marketplaces handling (#764)

---

src/feature/Users/UsersList.tsx

* [TRELLO-2730] Implement agent impersonification
* [TRELLO-2730] Format

MEP [TRELLO-2730] Implement agent impersonification (#767)

---

src/core/client/report/ReportNode.ts
src/core/client/report/ReportsClient.ts
src/feature/Stats/ArborescenceWithCounts.tsx

* [TRELLO-2861] Implement buttons to download countbysubcatgories
* [TRELLO-2861] Format

MEP [TRELLO-2861] Implement buttons to download countbysubcatgories (#782)

---

src/core/client/report/Report.ts
src/feature/Report/CategoryMessage.tsx
src/feature/Report/ReportHeader.tsx
src/feature/Reports/reportsColumns.tsx
src/feature/Subscriptions/SubscriptionCard.tsx
src/feature/Subscriptions/SubscriptionInformation.tsx
src/shared/SelectTags/SelectTags.tsx
src/shared/SelectTags/SelectTagsMenu.tsx

do not display it when listing the tags of a report do not suggest it in the filters

MEP TRELLO-2845 Hide Bloctel tag in a few places

---

src/core/plugins/Matomo.ts
src/feature/AdminTools/BlacklistedIpsTool.tsx
src/feature/Reports/ReportsFilter.tsx
src/shared/PeriodPickerWithPredefinedRanges.tsx

* [TRELLO-2889] Improved date picker (with predefined ranges)
* [TRELLO-2889] Use Popover instead of Dialog
* [TRELLO-2889] Some improvments
* [TRELLO-2889] Add forever range
* [TRELLO-2889] Remove dayjs, we already have date-fns

MEP [TRELLO-2889] Improved date picker (with predefined ranges) (#816)

---

src/conf/config.ts
src/core/client/async-file/AsyncFile.ts
src/core/client/report/ReportExport.ts
src/core/client/report/ReportsClient.ts
src/core/i18n/fr.ts
src/feature/Report/Report.tsx
src/feature/Report/ReportPro.tsx
src/feature/Report/reportDownload/ReportDownloadAction.tsx
src/feature/Report/reportDownload/reportDownloadUtils.ts
src/feature/ReportedPhones/ReportedPhones.tsx
src/feature/ReportedWebsites/ReportedUnknownWebsites.tsx
src/feature/Reports/AdvancedSearchBar.tsx
src/feature/Reports/DatatableToolbarComponent.tsx
src/feature/Reports/Reports.tsx
src/feature/ReportsPro/ReportsPro.tsx
src/shared/Datatable/DatatableToolbar.tsx
src/shared/ExportPopperBtn.tsx

This reverts commit c49ef1d8a25c4dabb2c2f8dc131de8f317ebc4d6.

Revert "Trello 2852 fix (#851)"

---

src/feature/ReportsPro/buildReportsProColumns.tsx

* [TRELLO-2964] Align mobile & desktop pro reports views
* [TRELLO-2964] Align mobile & desktop pro reports views

MEP [TRELLO-2964] Align mobile & desktop pro reports views (#873)

---

src/conf/config.ts
src/core/ScSidebar/ScSidebar.tsx
src/feature/CompaniesPro/CompaniesPro.tsx
src/feature/CompanyAccesses/CompanyAccesses.tsx

à merger quand effectivement on la supprime aussi cote backend

Remove accesses inheritance

---

src/alexlibs/mui-extension/Alert.tsx
src/alexlibs/mui-extension/color.ts
src/feature/Report/ReportAdminResolution.tsx
src/feature/Report/ReportPostAction.tsx
src/feature/Reports/AdvancedReportsFilter.tsx
src/shared/reportStatusUtils.ts

[TRELLO-3065] Improve accessibility

MEP Merge pull request #891 from betagouv/trello-3065

---

src/alexlibs/mui-extension/Btn.tsx
src/core/Layout/Layout.tsx
src/core/Layout/Sidebar/Sidebar.tsx
src/core/Layout/layoutConfig.ts
src/feature/AdminTools/BlacklistedIpsTool.tsx
src/feature/AdminTools/TestTools.tsx
src/feature/Companies/MassImport.tsx
src/feature/EmailValidation/EmailValidation.tsx
src/feature/JoinNewsletter/JoinNewsletter.tsx
src/feature/Report/ReportPro.tsx
src/feature/Report/ReportViewAsPro.tsx
src/feature/Settings/EditEmailDialog.tsx
src/feature/Settings/EditPasswordDialog.tsx
src/feature/Settings/EditProfileDialog.tsx
src/feature/Settings/Settings.tsx
src/feature/Users/UserActivation.tsx
src/shared/CenteredContent.tsx
src/shared/Page/Page.tsx

* [TRELLO-3065] Improve accessibility
* [TRELLO-3065] Improve accessibility
* [TRELLO-3065] Improve accessibility

MEP [TRELLO-3065] Improve accessibility (#899)
